### ISSUE TITLE
Create tests and github actions

### ISSUE THREAD

**Issue by IhabBendidi** [pinellolab/DNA-Diffusion#20]
- Add tests for all code functions
- Add github actions, for continuous testing of the code

**Comment by SauravMaheshkar** [comment]
Are we just looking for tests ? I'd also propose linters such as `black`, `isort` or `pylint`. At the moment we're at a nascent stage but it'd be nice to have automated linters before merging into main. We could also enforce linting using [`pre-commit`](https://pre-commit.com/) flags perhaps ?

Here's a [sample pylint CI](https://github.com/SauravMaheshkar/python-template/blob/main/.github/workflows/python.yml) actions file that I personally use with pytest.

**Comment by Johnny1188** [comment]
@IhabBendidi I heard that you had put together the initial structure for unit tests, have you got further than that? I'm asking because I've been assigned on the _Sprint 2 call_ to write unit tests for the code so far + for any new pull requests that will come in the upcoming days/weeks.

**Comment by IhabBendidi** [comment]
Hey @SauravMaheshkar I'm all in for linters too, do you want to work on that part?
@Johnny1188 I'm working on unit tests of the main diffusion functions, we can maybe split the other files between each other so that it would be faster, what do you think?
I will assign you both to this issue here

**Comment by Johnny1188** [comment]
Sounds good @IhabBendidi , I could start with the data loader and the unet (unet_lucas.py ... if it doesn't fall under the 'diffusion functions' u mentioned). Would you mind having a short call today/tomorrow? We can discuss the time on Discord - my username: **jan_s**

**Comment by SauravMaheshkar** [comment]
Sure, more than happy to work on the linters. I recommend using something like `pylint` because then we can use just one tool and one configuration file instead of having separate configuration files for `mypy`, `pytest`, `black`, `isort`, ...

I'll get started with a simple `pyproject.toml` configuration file for now.


@IhabBendidi do you think we should use `pre-commit` as well ? To enforce code quality even before pushing ?

**Comment by SauravMaheshkar** [comment]
I added a simple `pyproject.toml` along with a simple `requirements.txt` file in [71e9b64](https://github.com/pinellolab/DNA-Diffusion/pull/31/commits/71e9b642be314faac25f2258802d4485df1a604c).

**Comment by Johnny1188** [comment]
I just added tests for the `SequenceDataModule` (sequence dataloader) - see [pull request here](https://github.com/pinellolab/DNA-Diffusion/pull/41). Works with pytest.

**Comment by SauravMaheshkar** [comment]
Thanks @Johnny1188 I'd recommend merging #41 before this PR or should I rebase this branch @IhabBendidi ?

**Comment by mateibejan1** [comment]
Hey guys! Abraham (@owos) expressed his desire to help out and learn while doing so during yesterday's sprint planning & retro, so we decided that writing uni tests is a good place to start since he's gonna write a bit of torch code and understand how the codebase works. I hope you have nothing against coaching him on how to write the tests if he needs help!

**Comment by owos** [comment]
Thank you @mateibejan1

**Comment by SauravMaheshkar** [comment]
@owos I'm not contributing with tests. I just contributed for the Github Actions bit.

**Comment by Johnny1188** [comment]
@owos I think tests for utils are still missing (`/src/utils/`; tests for it go to `/tests/utils/`) so that could be a good start. You can take a look at the tests written for the data loader to see what the result might look like (`/tests/data/test_sequence_dataloader.py`).

**Comment by owos** [comment]
The folder `utils` folder is empty and there's `/tests` folder.

**Comment by Johnny1188** [comment]
**codebase** branch

**Comment by cameronraysmith** [comment]
This was addressed in #41 , but we'll factor this out into a smaller number of issues going forward.
