### ISSUE TITLE
Decide and implement evaluation metrics

### ISSUE THREAD

**Issue by NZ99** [pinellolab/DNA-Diffusion#6]

**Comment by miurazzo** [comment]
Hello guys, I have an idea of motif evaluation metric that I want to share. 

### KL divergence of latent features (factors) extracted from count of motifs per sequence. 

**Fact** : enhancers and Cis Regulatory Modules (aka our real DNA sequences and  generated sequences)  in general are functional because multiple motifs are bound to the sequence and act together to regulate gene expression. Therefore, it is expected that generated sequences using the diffusion model should contain, ideally,  a cluster of motifs. 

**Problem** : the current proposed motif metric is only counting the frequency of each motif on all sequences and comparing the proportion of counts between real sequences and generated sequences. One possible caveat is that no evaluation is done to confirm that synthetic sequences indeed have a cluster of motifs in a similar proportion to a given real sequence. Therefore, it is not known precisely if the model learned to generate functional sequences that resembles the structure of an enhancer. 

**Idea** : Consider the count of each motif match(aka: JASPAR vertebrates 2020) to each sequence as a feature of that observed sequence. Next, extract the latent features via  Factor Analysis or AutoEncoder to represent the motifs features in a smaller dimension. Since each motif feature could be described as a combination of latent features (factors), presumably those latent features describe the variance shared between motifs across sequences, aka: the mentioned functional cluster of motifs. With the latent features extracted,  the dataframe would be n x k, with n the number of sequences and k the number of latent features. 

There are some different approaches about how to use those latent features. One such approach is to assume that each latent feature could be described in a probability distribution. Therefore, we convert the latent feature to a probability distribution and compare the distribution on the real sequences with the distribution of the generated sequences using KL divergence. 

**Note**: since there are two datasets of sequences ( the real sequences and the generated sequences by the model) we would have to do two Factor Analysis and compare the factors between datasets. On the other hand, with an AutoEncoder trained on the real dataset, it  could be investigated if it is possible to extract the latent features and interpret them similarly to a Factor Analysis latent variables. If so, then the same AutoEncoder could extract the latent features for the real dataset and the generated dataset. Next, each latent feature is converted  to a probability distribution and compared between the two datasets via KL divergence or any probability distribution distance metric. 

**Note2**: in Factor Analysis, factors are assumed  not to be correlated. It could be verified if those latent factors can be distributed as independent univariate gaussians. If that is the case, then one could build a multivariate gaussian distribution of k dimensions (each representing the mean of each factor) and compare the gaussian of the real dataset with the gaussian of the generated via KL divergence. The KL divergence of two multivariate gaussian has closed form and such proof exists.

**Comment by LucasSilvaFerreira** [comment]
@miurazzo This factor analysis seems interesting. Maybe it can even be used when we separate the sequences in the different cell types. What kind of data you will need to explore it?  The counts for the real dataset and the motif counts on the synthetic sequences? How many sequences you will need? Do you think is it feasible to calculate it during training or it would be an "offline metric"? Let's see how fast will be the sampling when we finally start to use the cluster.

**Comment by miurazzo** [comment]
@LucasSilvaFerreira  thanks for your comment. The data needed is a dataframe where in each row a unique sequence is represented and in each column the motif match count. This can be obtained by filtering the output of gimme motif scan directly. 
About the number of sequences, in general for PCA and FA we expect that n >> k, where n is the number of rows( aka sequences) and k the number of features (aka columns). Usually PCA and FA is computed fast enough, but that depends on the dataframe size. I can verify if that is the case and report it here. 

I am still trying to think of a better solution to the problem of comparing factors between datasets, so Factor Analysis is just an initial idea that I though that could have a biological interpretation.

**Comment by cameronraysmith** [comment]
This issue is only being closed due to inactivity. Please feel free to reopen it if it is being worked on now or later.
